Update base_automl.py
mljar-supervised removes the Linear algorithm for dataset larger than 10,000 rows.
I had such dataset, and needed to see how Linear behaved.
If I set Linear as the only algorithm, I obtained this error:

supervised.exceptions.AutoMLException: No models produced.
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.

This is not a mljar-supervised bug.
I wonder this pull request is useful for others.